### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by tinoryj** [ustcadsl/depart#1]
During compilation I have some problems. After executing `ant clean & ant` I get the following output:
![image](https://user-images.githubusercontent.com/19286867/183895845-3307df89-1921-4ae0-95e9-1eaf242f6a18.png)
If I merge the source code into the underlying cassandra, it will report the following problems.
![image](https://user-images.githubusercontent.com/19286867/183895552-c35a1cc2-da05-4243-8e58-9fa1badfc698.png)
My open-jdk version is 11 and ant version is 1.10.7;

**Comment by CS0522** [comment]
You should delete 'build' folder, and modify some URLs in some place (sorry that I forgot where), replacing 'http://' with 'https://', and other some paths like '/home/distkv'. Then it should work.
